### ISSUE TITLE
[FEATURE] Edit events in the list screen

### ISSUE THREAD

**Issue by NicksPatties** [NicksPatties/timeclock#6]
**Is your feature request related to a problem? Please describe.**
I would like to edit the start time, end time, and/or name of completed events in case something goes wrong with recording items.

**Describe the solution you'd like**
Allow clicking on the fields in the open list item to open a dialogue to modify the time of the event. However, do not allow and editing event to start before the previous event, nor end after the start of the next event.

**Describe alternatives you've considered**
* Use time select pop up to capture time
* Use a variation of the EditTimerTextField to change times

**Additional context**
N/A

**Developer Notes**
* The functionality for this feature depends on whether or not recording multiple events at the same time is supported. If it is, then restrictions on start and end time are required, otherwise they are not. I will start by not supporting recording multiple events at once.

**Task breakdown**
- [ ] Create Edit Event view for open list item components
- [ ] Allow user to update an event's title
- [ ] Find the start and end time boundaries for a given event
- [ ] Allow user to update an event's start time or end time
- [ ] Update an event's end time via adjusting the total event time
